import asyncio
import dataclasses
import itertools
import json
import logging
import os
import traceback
from abc import ABC
from abc import abstractmethod
from copy import deepcopy
from dataclasses import dataclass
from enum import StrEnum
from typing import Dict
from typing import List
from typing import Optional
from typing import Union

import llamppl
import numpy as np
import tiktoken
from dotenv import load_dotenv
from openai import OpenAI
from vllm.engine.async_llm_engine import AsyncEngineDeadError
from vllm.model_executor.layers.sampler import Sampler
from vllm.sampling_params import BeamSearchParams
from vllm.sampling_params import SamplingParams
from vllm.utils import Counter

from disciple.base_models import BaseModel
from disciple.dev_models import UnconditionalSamplingModel
from disciple.inference import smc_standard
from disciple.model_generators import ModelGenerator
from disciple.model_generators import OpenAIModelGenerator
from evaluations.dataset import Task
from evaluations.model_registry import ModelRegistry

logger = logging.getLogger(__name__)

PIPELINES_DIR = "pipelines"


@dataclass
class InferenceResult:
    """Stores the results from a single sample/particle."""

    # Required
    pipeline_name: str
    task: Task
    N: int
    sampling_type: str

    # Attempt information
    attempt: int = 1
    is_final_attempt: bool = True

    # Optional (if inference was successful)
    text: str = None  # Answer text generated by the model
    full_text: str = None  # Full text including reasoning, if applicable
    sample_i: int = None
    weight: float = None
    finished: bool = None
    prompt: str = None
    check_result: bool = None  # Result of the model's check() method
    evaluate_results: Dict[str, bool] = (
        None  # Results of the dataset's evaluate() method
    )

    # Token counts
    prompt_tokens: int = None
    completion_tokens: int = None
    reasoning_tokens: int = None  # reasoning_tokens <= completion_tokens

    # Error info (optional)
    error_source: str = None
    error: str = None
    traceback: str = None


class SamplingType(StrEnum):
    INDEPENDENT = "independent"  # Draw N samples independently. Allows drawing max(N) samples and computing results retrospectively.
    ADAPTIVE = "adaptive"  # Draw N samples with potential interactions between samples. Requires running each value of N separately.
    SINGLE_SHOT = "single_shot"  # Only draw N=1 samples.


class InferencePipeline(ABC):
    def __init__(self, results_dir: str, **kwargs):
        self.results_dir = results_dir

    def __repr__(self):
        return f"{self.__class__.__name__}(results_dir={self.results_dir})"

    def __str__(self):
        return self.__repr__()

    @property
    def name(self):
        pass

    @property
    def sampling_type(self):
        return SamplingType.INDEPENDENT

    @property
    def cot(self):
        """Chain of Thought (CoT) reasoning."""
        return getattr(self, "_cot", False)

    @cot.setter
    def cot(self, value):
        """Set Chain of Thought (CoT) reasoning."""
        self._cot = value

    @property
    def system_prompt(self):
        if self.enable_manual_cot:
            return (
                "You are helping a user generate text that satisfies constraints. "
                "Think step-by-step in order to follow the user's instructions. "
                "Your final response should be enclosed in <answer></answer> tags."
            )
        else:
            return (
                "You are helping a user generate text that satisfies constraints. "
                "Follow the user's instructions exactly. Write your response below; "
                "do not preface your response or include any additional remarks."
            )

    @property
    def default_sent_prompt(self):
        return "Write a sentence that is grammatically correct and makes sense."

    def get_messages_for_task(self, task: Task, system_role: str = "system"):
        """Get chat messages for the task."""
        messages = []
        if system_role is not None:
            messages += [
                {
                    "role": system_role,
                    "content": self.system_prompt,
                }
            ]
        messages += [{"role": "user", "content": task.prompt}]
        if system_role is not None and self.enable_manual_cot:
            messages += [
                {
                    "role": system_role,
                    "content": (
                        "REMEMBER: Your final response should be enclosed in <answer></answer> tags."
                    ),
                }
            ]
        return messages

    def parse_answer(self, text: str) -> str:
        """Parse the answer from the text. If CoT is enabled, extract the answer from <answer></answer> tags. Otherwise, return the text as is.

        If the text does not contain <answer></answer> tags, return the text as is.
        """
        if self.enable_manual_cot:
            start_tag = "<answer>"
            end_tag = "</answer>"
            start_idx = text.find(start_tag)
            end_idx = text.find(end_tag, start_idx + len(start_tag))
            if start_idx != -1 and end_idx != -1:
                return text[start_idx + len(start_tag) : end_idx]
        return text

    async def generate_model(self, task: Task, **kwargs) -> Optional[BaseModel]:
        """Generate an InferenceModel class for a task. Intentional no-op for baselines."""
        pass

    @abstractmethod
    async def infer(self, task: Task, N: int, **kwargs) -> List[InferenceResult]:
        """Run inference on a task."""
        pass

    async def __call__(
        self, task: Task, N: Union[int, List[int]], **kwargs
    ) -> List[InferenceResult]:
        if isinstance(N, int):
            N = [N]

        results_list = []

        if self.sampling_type == SamplingType.SINGLE_SHOT:
            N = [1]
        elif self.sampling_type == SamplingType.INDEPENDENT:
            N = [max(N)]
        elif self.sampling_type == SamplingType.ADAPTIVE:
            pass
        else:
            raise ValueError(f"Unknown sampling type: {self.sampling_type}")

        for n in N:
            results_n = await self.infer(task, n, **kwargs)
            assert len(results_n) == n
            results_list += results_n

        assert len(results_list) == sum(N)
        return results_list


pipeline_registry = {}


def register_pipeline(name):
    def decorator(cls):
        cls.name = name
        pipeline_registry[name] = cls
        return cls

    return decorator


def pipeline_factory(config: Dict) -> InferencePipeline:
    pipeline_type = config["type"]
    params = config.get("params", {})

    if pipeline_type in pipeline_registry:
        return pipeline_registry[pipeline_type](**params)
    else:
        raise ValueError(f"Unknown pipeline type: {pipeline_type}")


def load_pipelines_from_configs(
    config_files: List[str], results_dir: str, params: Dict = {}
) -> List[InferencePipeline]:
    """Load pipelines from a list of config files.

    Args:
        config_files: List of config file names (without the ".json" extension).
        results_dir: Directory to store results. Each pipeline will have its own subdirectory.
        params: Additional parameters to pass to the pipelines.
            Overwrites any existing values for these params in the config files.

    """
    pipeline_list = []
    for config_file in config_files:
        config_path = os.path.join(
            os.path.dirname(__file__), "configs", f"{config_file}.json"
        )
        with open(config_path, "r") as f:
            config = json.load(f)
        _params = dict(params)
        _params["results_dir"] = os.path.join(
            results_dir, PIPELINES_DIR, config.get("name", config["type"])
        )

        # Avoid overwriting with None values
        def deep_update(orig, update):
            for key, value in update.items():
                if value is None:
                    continue
                if isinstance(value, dict) and isinstance(orig.get(key), dict):
                    deep_update(orig[key], value)
                else:
                    orig[key] = value

        deep_update(config["params"], _params)

        pipeline = pipeline_factory(config)

        # update pipeline name from config
        if "name" in config:
            pipeline.name = config["name"]

        # Ensure unique pipeline names
        if pipeline.name in set([p.name for p in pipeline_list]):
            raise ValueError(f"Duplicate pipeline name detected: {pipeline.name}")

        pipeline_list.append(pipeline)

    return pipeline_list


class SMCInferencePipeline(InferencePipeline):
    def __init__(self, results_dir: str, **kwargs):
        super().__init__(results_dir)

    @property
    def sampling_type(self):
        return SamplingType.ADAPTIVE

    async def infer(
        self,
        task: Task,
        N: int,
        model_cls: BaseModel,
        lm: llamppl.CachedCausalLM,
        use_proposal: bool = True,
        max_tokens: int = 32,
        temperature: float = 1.0,
        ess_threshold: float = 0.5,
        timeout: float = 120.0,
        max_steps: int = 1000,
        cache_kv: bool = True,
        visualize: bool = False,
        **kwargs,
    ) -> List[InferenceResult]:
        """Run SMC inference with the model_cls."""
        assert isinstance(N, int)
        lm.batch_size = N

        try:
            model = await model_cls.create(
                lm=lm,
                task_prompt=task.prompt,
                max_tokens=max_tokens,
                temperature=temperature,
            )
        except AsyncEngineDeadError as e:
            raise e
        except Exception as e:
            logger.error(f"Model initialization failed")
            return [
                InferenceResult(
                    pipeline_name=self.name,
                    task=task,
                    N=N,
                    sampling_type=str(self.sampling_type),
                    error_source="model_init",
                    error=str(e),
                    traceback=traceback.format_exc(),
                )
            ] * N

        logger.info(f"Running SMC inference ({N} particles, timeout={timeout}s)")
        try:
            # Context manager requires Python 3.11+
            async with asyncio.timeout(timeout):
                particles = await smc_standard(
                    model,
                    n_particles=N,
                    ess_threshold=ess_threshold,
                    max_steps=max_steps,
                    visualize=visualize,
                )
        except AsyncEngineDeadError as e:
            raise e
        except (asyncio.TimeoutError, TimeoutError) as e:
            lm.reset_async_queries()
            return [
                InferenceResult(
                    pipeline_name=self.name,
                    task=task,
                    N=N,
                    sampling_type=str(self.sampling_type),
                    error_source="smc_standard",
                    error=f"TimeoutError(timeout={timeout})",
                    traceback=f"Inference timed out after {timeout} seconds. Check the InferenceModel to ensure loop termination.",
                )
            ] * N
        except Exception as e:
            lm.reset_async_queries()
            return [
                InferenceResult(
                    pipeline_name=self.name,
                    task=task,
                    N=N,
                    sampling_type=str(self.sampling_type),
                    error_source="smc_standard",
                    error=str(e),
                    traceback=traceback.format_exc(),
                )
            ] * N

        # Check to ensure all particles are done stepping
        if not all(p.done_stepping() for p in particles):
            lm.reset_async_queries()
            return [
                InferenceResult(
                    pipeline_name=self.name,
                    task=task,
                    N=N,
                    sampling_type=str(self.sampling_type),
                    error_source="smc_standard",
                    error=f"Max inference steps exceeded (t={max_steps})",
                    traceback=f"Max steps inference exceeded (t={max_steps}). Check the InferenceModel to ensure it includes self.finish() and loops are properly terminated.",
                )
            ] * N

        def _convert_weight_to_float(weight):
            """Convert weight to float, handling various types.

            NOTE: This is a corner case that occurs with Qwen3 models and needs debugging.
            """
            try:
                return float(weight)
            except:
                pass

            logger.warning(
                f"Unable to convert weight to float: type {type(weight)}, value: {weight}"
            )
            if isinstance(weight, np.ndarray):
                if weight.size == 0:
                    logger.warning("Particle weight is empty array, returning -inf.")
                    return float("-inf")
                elif weight.size == 1:
                    return float(weight.item())

            raise ValueError(f"Unexpected weight: type {type(weight)}, value: {weight}")

        return [
            InferenceResult(
                pipeline_name=self.name,
                task=task,
                N=N,
                sampling_type=str(self.sampling_type),
                text=str(p),
                completion_tokens=p.context.token_count,
                prompt_tokens=p.context.prompt_token_count,
                sample_i=i,
                weight=_convert_weight_to_float(p.weight),
                finished=p.finished,
                prompt=task.prompt,
                check_result=p.check_result,
                evaluate_results=task.evaluate(str(p)),
            )
            for i, p in enumerate(particles)
        ]


@register_pipeline("unconditional_sampling")
class UnconditionalSamplingPipeline(SMCInferencePipeline):
    def __init__(self, results_dir: str, **kwargs):
        super().__init__(results_dir)

    @property
    def sampling_type(self):
        return SamplingType.INDEPENDENT

    async def generate_model(self, task: Task, **kwargs) -> UnconditionalSamplingModel:
        return UnconditionalSamplingModel


@register_pipeline("disciple_smc")
class DisciplePipeline(SMCInferencePipeline):
    def __init__(
        self,
        results_dir: str,
        model_generator_params: Dict,
        dataset_name: str = None,
        n_attempts: int = 1,
        oracle: bool = False,
        **kwargs,
    ):
        self.dataset_name = dataset_name
        self.n_attempts = n_attempts

        # Initialize the model generator
        self.model_generator = None
        model_generator_dir = os.path.join(
            results_dir, ModelGenerator.DEFAULT_MODEL_DIR_BASE
        )

        # Lazy load models from another pipeline, assuming `load_models_from_pipeline` is a pipeline name in the same directory
        if model_generator_params.get("load_models_from_pipeline") is not None:
            if model_generator_params.get("load_models_from_path") is not None:
                logger.warning(
                    f"Both `load_models_from_pipeline` and `load_models_from_path` are specified for {self.name}. Using `load_models_from_pipeline`."
                )
            model_generator_dir = os.path.join(
                os.path.dirname(results_dir),
                model_generator_params["load_models_from_pipeline"],
                ModelGenerator.DEFAULT_MODEL_DIR_BASE,
            )
        # Non-lazy load models from a prior run
        elif model_generator_params.get("load_models_from_path") is not None:
            self.model_generator = OpenAIModelGenerator.load_from(
                openai_model=model_generator_params.get("openai_model"),
                existing_model_dir=os.path.join(
                    model_generator_params["load_models_from_path"],
                    PIPELINES_DIR,
                    self.name,
                    ModelGenerator.DEFAULT_MODEL_DIR_BASE,
                ),
                new_model_dir=model_generator_dir,
                cache_behavior=model_generator_params.get("cache_behavior"),
                debug_mode=model_generator_params.get("debug_mode"),
                use_reasoning=model_generator_params.get("use_reasoning"),
                include_feedback=self.n_attempts > 1,
                generate_step_fn=model_generator_params.get("generate_step_fn", True),
                generate_check_fn=model_generator_params.get("generate_check_fn", True),
            )

        # Initialize the model generator
        if self.model_generator is None:
            self.model_generator = OpenAIModelGenerator(
                openai_model=model_generator_params.get("openai_model"),
                model_dir=model_generator_dir,
                cache_behavior=model_generator_params.get("cache_behavior"),
                debug_mode=model_generator_params.get("debug_mode"),
                use_reasoning=model_generator_params.get("use_reasoning"),
                include_feedback=self.n_attempts > 1,
                generate_step_fn=model_generator_params.get("generate_step_fn", True),
                generate_check_fn=model_generator_params.get("generate_check_fn", True),
            )

        # Oracle mode: Include example models that are already in the task's task_types
        self.oracle = oracle

        super().__init__(results_dir)

    @property
    def sampling_type(self):
        return SamplingType.ADAPTIVE

    async def generate_model(
        self, task: Task, example_models: List[Dict], version: int = 1, **kwargs
    ) -> Optional[BaseModel]:
        """Uses ModelGenerator to generate an inference model class."""
        return self.model_generator(
            task=task, example_models=example_models, version=version, **kwargs
        )

    async def __call__(
        self,
        task: Task,
        N: Union[int, List[int]],
        lm: llamppl.CachedCausalLM,
        **kwargs,
    ) -> List[InferenceResult]:
        if isinstance(N, int):
            N = [N]

        results_by_attempt = await self._run_disciple_loop(task, N, lm, **kwargs)

        return list(itertools.chain(*results_by_attempt))

    async def _run_disciple_loop(
        self,
        task: Task,
        N: List[int],
        lm: llamppl.CachedCausalLM,
        **kwargs,
    ) -> List[InferenceResult]:

        example_models = self.load_example_models(task, oracle=self.oracle)

        results_by_attempt: List[List[InferenceResult]] = []

        for attempt_i in range(1, self.n_attempts + 1):

            ########################################
            # Generate model
            ########################################
            model_generation_result = await self.generate_model(
                task, example_models=example_models, version=attempt_i
            )
            if model_generation_result.error is not None:
                logger.error(
                    f"Model generation failed (attempt {attempt_i}/{self.n_attempts})"
                )
                logger.error(model_generation_result.traceback)
                results_attempt = []
                for n in N:
                    results_attempt += [
                        InferenceResult(
                            pipeline_name=self.name,
                            task=task,
                            N=n,
                            sampling_type=str(self.sampling_type),
                            attempt=attempt_i,
                            is_final_attempt=False,
                            error_source="model_generation",
                            error=model_generation_result.error,
                            traceback=model_generation_result.traceback,
                        )
                    ] * n
                results_by_attempt.append(results_attempt)

                # Add feedback to example_models
                example_models.append(
                    {
                        "prompt": task.prompt,
                        "model_source": model_generation_result.source,
                        "traceback": model_generation_result.traceback,
                    }
                )

                continue

            ########################################
            # Run inference with generated model
            ########################################
            results_attempt: List[InferenceResult] = []
            is_model_valid = True

            # Clear LM cache
            lm.clear_cache()
            lm.reset_async_queries()

            inference_error = None
            for n in N:

                if is_model_valid:
                    results_n = await self.infer(
                        task, n, model_generation_result.cls, lm, **kwargs
                    )

                    # Handle runtime errors during inference
                    if results_n[0].error is not None:
                        inference_error = results_n[0]
                        is_model_valid = False
                        logger.error(
                            f"Inference failed (attempt {attempt_i}/{self.n_attempts})"
                        )
                        logger.error(inference_error.traceback)

                        # Add feedback to example_models
                        example_models.append(
                            {
                                "prompt": task.prompt,
                                "model_source": model_generation_result.source,
                                "traceback": inference_error.traceback,
                            }
                        )
                else:
                    results_n = [inference_error] * n

                # Update results with attempt number and number of particles
                # NOTE: This is done even if the model is invalid so that errors are propagated
                results_attempt += [
                    dataclasses.replace(
                        result,
                        N=n,
                        attempt=attempt_i,
                        is_final_attempt=False,
                    )
                    for result in results_n
                ]

            results_by_attempt.append(results_attempt)

            if is_model_valid:
                break

        # Clear LM cache
        lm.clear_cache()
        lm.reset_async_queries()

        for results_attempt in results_by_attempt:
            assert len(results_attempt) == sum(N)

        # Mark all results in the last attempt as final
        for r in results_by_attempt[-1]:
            r.is_final_attempt = True

        return results_by_attempt

    def load_example_models(self, task: Task, oracle: bool = False) -> List[Dict]:
        """Load example models for a task. Hold out models that are already in the task's task_types.

        Args:
            task: Task object.
            oracle: Whether to include models that are already in the task's task_types.
        """
        model_registry = ModelRegistry()
        example_models = []
        for data in model_registry.registry.values():
            if oracle or not any(
                task_type == data["task_type"] for task_type in task.task_types
            ):
                example_models.append(
                    {
                        "prompt": data["prompt"],
                        "reasoning": data["reasoning"],
                        "model_source": self.model_generator.get_source_from_class(
                            data["model_class"], obfuscate_classnames=True
                        ),
                    }
                )
        if len(example_models) == 0:
            logger.warning(
                f"WARNING: No example models found (dataset={self.dataset_name}, task_types={task.task_types})"
            )
        return example_models


@register_pipeline("disciple_importance")
class DiscipleImportancePipeline(DisciplePipeline):
    """Disciple pipeline that uses importance sampling instead of SMC.

    This is implemented by running smc_standard with ess_threshold=0 so that resampling never occurs.
    """

    def __init__(self, results_dir: str, **kwargs):
        super().__init__(results_dir, **kwargs)

    @property
    def sampling_type(self):
        return SamplingType.INDEPENDENT

    async def __call__(
        self,
        task: Task,
        N: Union[int, List[int]],
        lm: llamppl.CachedCausalLM,
        **kwargs,
    ) -> List[InferenceResult]:
        if isinstance(N, int):
            N = [N]

        # Run max(N) particles
        results_by_attempt = await self._run_disciple_loop(task, [max(N)], lm, **kwargs)

        # Return flattened results list
        return list(itertools.chain(*results_by_attempt))

    async def infer(
        self,
        task: Task,
        N: int,
        model_cls: BaseModel,
        lm: llamppl.CachedCausalLM,
        max_tokens: int = 32,
        temperature: float = 0.7,
        ess_threshold=0.0,
        timeout: float = 120.0,
        **kwargs,
    ) -> List[InferenceResult]:
        return await super().infer(
            task,
            N,
            model_cls,
            lm,
            max_tokens=max_tokens,
            temperature=temperature,
            ess_threshold=0.0,
            timeout=timeout,
            **kwargs,
        )


@register_pipeline("disciple_rejection")
class DiscipleRejectionPipeline(DiscipleImportancePipeline):
    """Disciple pipeline that uses rejection sampling instead of SMC.

    This is implemented by replacing the step() method with a single-step method that generates until EOS.
    """

    @property
    def sampling_type(self):
        return SamplingType.INDEPENDENT

    def __init__(self, results_dir: str, model_generator_params: Dict, **kwargs):
        model_generator_params["generate_step_fn"] = False
        super().__init__(
            results_dir, model_generator_params=model_generator_params, **kwargs
        )


@register_pipeline("vllm")
class VLLMPipeline(InferencePipeline):
    def __init__(
        self, results_dir: str, beam_search: bool = False, cot: bool = False, **kwargs
    ):
        super().__init__(results_dir)
        self.beam_search = beam_search
        self.enable_manual_cot = cot  # Chain of Thought (CoT) reasoning

        self.request_counter = Counter()

    @property
    def sampling_type(self):
        return SamplingType.ADAPTIVE if self.beam_search else SamplingType.INDEPENDENT

    async def infer(
        self,
        task: Task,
        N: int,
        lm: llamppl.CachedCausalLM,
        temperature: float = 0.7,
        max_tokens: int = 32,
        timeout: float = 120.0,
        **kwargs,
    ) -> List[InferenceResult]:
        assert isinstance(N, int)

        if lm.backend != "vllm":
            raise ValueError(
                f"VLLMPipeline requires `backend=vllm` (current `backend={lm.backend}`)."
            )

        # Ensure the model has a Sampler
        if not isinstance(
            lm.model.async_llm_engine.engine.model_executor.driver_worker.model_runner.model.sampler,
            Sampler,
        ):
            logging.warning(
                f"VLLMPipeline expected model.sampler to be a Sampler, but found {type(lm.model.async_llm_engine.engine.model_executor.driver_worker.model_runner.model.sampler)}. Replacing with Sampler."
            )
            lm.model.async_llm_engine.engine.model_executor.driver_worker.model_runner.model.sampler = (
                Sampler()
            )

        model, tokenizer = lm.model, lm.tokenizer

        messages = self.get_messages_for_task(task)
        prompt = tokenizer.apply_chat_template(
            conversation=messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
        req_id = f"vllm_pipeline_{next(self.request_counter)}"

        if self.beam_search:
            # NOTE: currently there is a bug in vLLM when N > 20
            # https://github.com/vllm-project/vllm/issues/10792
            beam_search_params = BeamSearchParams(
                beam_width=N,
                temperature=temperature,
                max_tokens=max_tokens,
                ignore_eos=False,
            )
            generator = model.async_llm_engine.beam_search(
                prompt=prompt,
                params=beam_search_params,
                request_id=req_id,
            )
        else:
            sampling_params = SamplingParams(
                n=N,
                temperature=temperature,
                max_tokens=max_tokens,
                logprobs=1,
                ignore_eos=False,
            )
            generator = model.async_llm_engine.generate(
                prompt=prompt,
                sampling_params=sampling_params,
                request_id=req_id,
            )

        results = []
        async for request in generator:
            if request.finished:
                for i, output in enumerate(request.outputs):
                    results.append(
                        InferenceResult(
                            pipeline_name=self.name,
                            task=task,
                            N=N,
                            sampling_type=str(self.sampling_type),
                            text=self.parse_answer(output.text),
                            full_text=output.text,
                            completion_tokens=len(output.token_ids),
                            sample_i=i,
                            weight=float(output.cumulative_logprob),
                            finished=output.finish_reason == "stop",
                            prompt=prompt,
                            evaluate_results=task.evaluate(output.text),
                        )
                    )

        return results


@register_pipeline("huggingface")
class HuggingFacePipeline(InferencePipeline):
    def __init__(
        self, results_dir: str, beam_search: bool = False, cot: bool = False, **kwargs
    ):
        super().__init__(results_dir)
        self.beam_search = beam_search
        self.enable_manual_cot = cot

    @property
    def sampling_type(self):
        return SamplingType.ADAPTIVE if self.beam_search else SamplingType.INDEPENDENT

    async def infer(
        self,
        task: Task,
        N: int,
        lm: llamppl.CachedCausalLM,
        temperature: float = 0.7,
        max_tokens: int = 32,
        timeout: float = 120.0,
        **kwargs,
    ) -> List[InferenceResult]:
        """Calls the Hugging Face API N times."""
        assert isinstance(N, int)

        if lm.backend != "hf":
            raise ValueError(
                f"HuggingFacePipeline requires `backend=hf` (current `backend={lm.backend}`)."
            )

        model, tokenizer = lm.model.model, lm.tokenizer

        # NOTE: llama3 tokenizer does not have a pad_token_id so this is a workaround
        # We can't use tokenizer.eos_token_id because we need to distinguish between padding and end-of-sequence
        pad_token_id = tokenizer.pad_token_id or len(tokenizer.vocab) - 1

        messages = self.get_messages_for_task(task)
        prompt = tokenizer.apply_chat_template(
            conversation=messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )

        # Generate N samples
        if self.beam_search:
            prompts = prompt
        else:
            prompts = [prompt] * N

        inputs = tokenizer(prompts, return_tensors="pt").to(model.device)
        input_length = inputs.input_ids.shape[1]
        outputs = model.generate(
            **inputs,
            # tokens
            max_new_tokens=max_tokens,
            pad_token_id=pad_token_id,
            # beam search
            num_beams=N if self.beam_search else 1,
            num_return_sequences=N if self.beam_search else 1,
            # sampling
            do_sample=temperature > 0,
            temperature=temperature if temperature > 0 else None,
            top_p=1.0,
            top_k=None,
            # timeouts
            max_time=timeout,
            # output formats
            return_dict_in_generate=True,
            output_scores=True,
        )
        generated_tokens = outputs.sequences[:, input_length:]
        generated_text = tokenizer.batch_decode(
            generated_tokens, skip_special_tokens=True
        )

        pad_mask = generated_tokens != pad_token_id

        # Compute sequence logprobs
        transition_scores = model.compute_transition_scores(
            sequences=outputs.sequences,
            scores=outputs.scores,
            beam_indices=outputs.beam_indices if self.beam_search and N > 1 else None,
            normalize_logits=True,
        )
        transition_scores *= pad_mask
        sequence_scores = transition_scores.sum(dim=-1).flatten()

        # Compute token counts
        token_counts = pad_mask.sum(dim=-1).flatten()

        return [
            InferenceResult(
                pipeline_name=self.name,
                task=task,
                N=N,
                sampling_type=str(self.sampling_type),
                text=self.parse_answer(generated_text[i]),
                full_text=generated_text[i],
                completion_tokens=token_counts[i].item(),
                sample_i=i,
                weight=sequence_scores[i].item(),
                finished=True,
                prompt=prompt,
                evaluate_results=task.evaluate(generated_text[i]),
            )
            for i in range(N)
        ]


@register_pipeline("openai")
class OpenAIPipeline(InferencePipeline):

    DEFAULT_OPENAI_MODEL = "gpt-4o-mini"

    def __init__(
        self,
        results_dir: str,
        openai_model: str = DEFAULT_OPENAI_MODEL,
        cot: bool = False,
        **kwargs,
    ):
        super().__init__(results_dir)
        load_dotenv()
        self.openai_model = openai_model
        self.enable_manual_cot = cot
        self.is_reasoning_model = False
        self.client = OpenAI()
        self.supports_temperature = True
        self.supports_logprobs = True
        self.system_role = "system"

    @property
    def sampling_type(self):
        return SamplingType.INDEPENDENT

    def get_completions_path(self, task: Task):
        return os.path.join(
            self.results_dir,
            f"task_{task.task_id:04d}",
            f"completion.json",
        )

    async def infer(
        self,
        task: Task,
        N: int,
        temperature: float = 0.7,
        max_tokens: int = 32,
        **kwargs,
    ) -> List[InferenceResult]:
        """Calls the OpenAI API N times."""
        assert isinstance(N, int)

        messages = self.get_messages_for_task(task, system_role=self.system_role)

        completion_kwargs = dict(
            model=self.openai_model,
            messages=messages,
            n=N,
            max_completion_tokens=max_tokens,
        )
        if self.supports_temperature:
            completion_kwargs["temperature"] = temperature
        if self.supports_logprobs:
            completion_kwargs["logprobs"] = True
        response = self.client.chat.completions.create(**completion_kwargs)

        # Save completions to file
        if self.results_dir is not None:
            completion_path = self.get_completions_path(task)
            os.makedirs(os.path.dirname(completion_path), exist_ok=True)
            with open(completion_path, "w") as f:
                f.write(response.model_dump_json(indent=4))

        # TODO: Handle errors in response
        results = []
        for i, choice in enumerate(response.choices):
            completion_text = choice.message.content
            answer_text = self.parse_answer(completion_text)

            # prompt_tokens is shared across all choices
            prompt_tokens = response.usage.prompt_tokens
            # Since OpenAI doesn't give completion token breakdown per choice for N > 1, we manually count tokens
            completion_tokens = self.count_tokens(completion_text)

            if self.is_reasoning_model:
                assert N == 1
                reasoning_tokens = (
                    response.usage.completion_tokens_details.reasoning_tokens
                )
            elif self.enable_manual_cot:
                reasoning_tokens = completion_tokens - self.count_tokens(answer_text)
            else:
                reasoning_tokens = 0

            result = InferenceResult(
                pipeline_name=self.name,
                task=task,
                N=N,
                sampling_type=str(self.sampling_type),
                text=answer_text,
                full_text=completion_text,
                completion_tokens=completion_tokens,
                prompt_tokens=prompt_tokens,
                reasoning_tokens=reasoning_tokens,
                sample_i=i,
                weight=(
                    self.compute_sequence_logprob(choice)
                    if self.supports_logprobs
                    else None
                ),
                finished=choice.finish_reason == "stop",
                prompt=self.apply_chat_template(messages),
                evaluate_results=task.evaluate(answer_text),
            )
            results.append(result)
        return results

    @staticmethod
    def get_encoding_for_model(model_name: str):
        return tiktoken.encoding_for_model(model_name)

    def count_tokens(self, text: str):
        """Count the number of tokens in the text."""
        encoding = self.get_encoding_for_model(self.openai_model)
        return len(encoding.encode(text))

    def apply_chat_template(
        self, messages, add_generation_prompt=False, tokenize=False
    ):
        """Adapted from: https://github.com/melisa-writer/tiktoken-chatml"""
        encoding = self.get_encoding_for_model(self.openai_model)
        prompt = ""
        for msg in messages:
            prompt += f"<|im_start|>{msg['role']}\n{msg['content']}\n<|im_end|>\n"
        prompt = prompt.strip()
        if add_generation_prompt:
            prompt += "\n<|im_start|>assistant\n"
        if tokenize:
            return encoding.encode(prompt, allowed_special="all")
        return prompt

    def compute_sequence_logprob(self, choice):
        """Compute the log probability of the sequence by summing the logprobs of each token."""
        return sum([token_logprob.logprob for token_logprob in choice.logprobs.content])


@register_pipeline("openai_o1")
class OpenAIO1Pipeline(OpenAIPipeline):

    DEFAULT_O1_MODEL = "o1-2024-12-17"
    MAX_COMPLETION_TOKENS = 25000

    def __init__(
        self, results_dir: str, openai_model: str = DEFAULT_O1_MODEL, **kwargs
    ):
        if not openai_model.startswith("o1"):
            raise ValueError(
                "OpenAIO1Pipeline requires an o1 model (model name must start with 'o1')."
            )
        super().__init__(results_dir, openai_model=openai_model, **kwargs)

        self.supports_temperature = False
        self.supports_logprobs = False
        self.system_role = None

        # CoT reasoning is enabled by default in o1 models, so we don't need to use a CoT prompt
        self.is_reasoning_model = True
        self.enable_manual_cot = False

    @property
    def sampling_type(self):
        return SamplingType.SINGLE_SHOT

    async def infer(
        self,
        task: Task,
        N: int = 1,
        **kwargs,
    ) -> List[InferenceResult]:
        assert N == 1, "OpenAIO1Pipeline only supports N=1 (single-shot inference)."
        results = await super().infer(
            task, N, temperature=None, max_tokens=self.MAX_COMPLETION_TOKENS
        )
        return results

    @staticmethod
    def get_encoding_for_model(model_name: str):
        # For o1 models, use the specific encoding
        # TODO (2025-01-29): o1-prefix is defined in tiktoken 0.8.0 but we're currently not able to upgrade due to dependency issues with `mistral_common`
        return tiktoken.get_encoding("o200k_base")
